name: Publish Package

on:
  push:
    tags:
      - 'v*'


jobs:
  publish:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: Release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run vite-build

      # - name: Test All
      #   run: npm run test:all
                
      # - name: Update coverage badge
      #   run: npm run coverageBadge

      - name: Publish to npm
        run: npm publish --provenance --access public

      # - name: Generate Changelog
      #   run: npx changelogithub
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}